In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [2]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [3]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [8]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [9]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
y_train.shape

(8000, 11)

In [12]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train.shape

11

In [7]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

c:\users\cufar\anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [8]:
#Initializing Neural Network
classifier = Sequential()

In [9]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

c:\users\cufar\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, kernel_initializer="uniform", input_dim=11, activation="relu")`
  
c:\users\cufar\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, kernel_initializer="uniform", activation="relu")`
  """
c:\users\cufar\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="uniform", activation="sigmoid")`
  


In [10]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [11]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

c:\users\cufar\anaconda3\envs\tensorflow\lib\site-packages\keras\models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.4910 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4220 - acc: 0.7965
Epoch 3/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4160 - acc: 0.7979
Epoch 4/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4124 - acc: 0.8252
Epoch 5/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.4096 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4082 - acc: 0.8324
Epoch 7/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4064 - acc: 0.8332
Epoch 8/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4052 - acc: 0.8355
Epoch 9/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4040 - acc: 0.8357
Epoch 10/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4030 - acc: 0.8360

8000/8000 [==============================] - 1s 153us/step - loss: 0.3926 - acc: 0.8382
Epoch 83/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.3924 - acc: 0.8367
Epoch 84/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.3923 - acc: 0.8370
Epoch 85/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.3925 - acc: 0.8372
Epoch 86/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3922 - acc: 0.8392
Epoch 87/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3923 - acc: 0.8384
Epoch 88/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.3926 - acc: 0.8351
Epoch 89/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.3926 - acc: 0.8385
Epoch 90/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.3927 - acc: 0.8362
Epoch 91/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.3922 - acc: 0.8370
Epo

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [14]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1535,   56],
       [ 280,  129]], dtype=int64)